### ISSUE TITLE
Stripe Docs are incorrect

### ISSUE THREAD

**Issue by toomanylogins** [stripe-samples/github-pages-stripe-checkout#8]
# Bug report
This page is incorrect out of date. https://stripe.com/docs/payments/checkout/shipping
## Describe the bug

    shipping_address_collection: {
      allowed_countries: ['US', 'CA'],
    },

should be 

https://stripe.com/docs/js/checkout/redirect_to_checkout#stripe_checkout_redirect_to_checkout-options-shippingAddressCollection

shippingAddressCollection: {
                            allowedCountries:

**Comment by cjavilla-stripe** [comment]
Sorry for any confusion. When working with the redirection on the client side, use camel case, when on the server side with stripe-node use snake case. Also, we recommend against using client side checkout redirection as it's quite limited. Instead, we recommend using either Payment Links: https://stripe.com/payments/payment-links or server side redirects with Checkout.
